name: Deploy on AWS EC2

on:
  push:
    branches:
      - main
      - ec2-deployment # only for testing on ec2-deployment branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up node environment
      uses: actions/setup-node@v3
      with:
        node-version: 17

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Run build
      run: npm run build

    - name: Deploy to EC2 instance
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}

