name: Deploy on AWS EC2

on:
  push:
    branches:
      - main
      - ec2-deployment # only for testing on ec2-deployment branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Deploy to EC2 instance
    #   uses: easingthemes/ssh-deploy@v2.1.5
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
    #     SOURCE: "./"
    #     REMOTE_HOST: "ec2-44-201-254-140.compute-1.amazonaws.com"
    #     REMOTE_USER: "ec2-user"
    #     TARGET: "/home/ec2-user/porfolio"

